### ISSUE TITLE
FIX - Problema com search

### ISSUE THREAD

**Issue by pabloedu01** [TUNAP-Brasil/vehicle_control#125]
https://github.com/TUNAP-Brasil/vehicle_control/assets/1905753/664f7af8-7245-4729-963a-7e5be9a84a11

**Comment by serpams** [comment]
- Adiciona Search a estes parametros 
- Adiciona pagintate
Parametros defaults - current_page=1  e limit = 10

**Comment by pabloedu01** [comment]
Ok.
