### ISSUE TITLE
Solucionar problema con CORS

### ISSUE THREAD

**Issue by pabloedu01** [TUNAP-Brasil/vehicle_control#27]
Solucione el problema con CORS en el sitio web

siempre tenemos que comentar el archivo app/Http/Kernel.php

Line  "\Fruitcake\Cors\HandleCors::class,

**Comment by serpams** [comment]
Em meus testes em outros servidores
identifiquei varios conflitos quando usado com o apache
porém com o nginx ele funciona  o cors do laravel 
existem algumas bloqueios de rewrite no .htaccess e no conf do apache se tiver redundante ele bloqueia
