### ISSUE TITLE
Retornar menú de ajustes

### ISSUE THREAD

**Issue by pabloedu01** [TUNAP-Brasil/vehicle_control#29]
![image](https://user-images.githubusercontent.com/1905753/183665141-a834e62d-0989-4e52-9b23-5f5addf84cd3.png)

Retornar menú de ajustes conforme o modelo a seguir

https://hyper-ashen.vercel.app/apps/ecommerce/orders
![image](https://user-images.githubusercontent.com/1905753/183665369-d591401a-72d0-4f13-a154-b8653f103e18.png)

Com todas as funções

**Comment by ccccastanho001** [comment]
quais as  funções ?

**Comment by serpams** [comment]
reenviar arquivo do tema base

**Comment by pabloedu01** [comment]
Enviado no Telegram.

**Comment by pabloedu01** [comment]
Essa alteração ficou quebrada, não está funcionando no site inteiro
