### ISSUE TITLE
Alterar incluir nome de usuário

### ISSUE THREAD

**Issue by pabloedu01** [TUNAP-Brasil/vehicle_control#30]
![image](https://user-images.githubusercontent.com/1905753/183668039-ecb6daaa-3cde-4c8b-a817-f79ea87d4ceb.png)

Incluír username no lugar de "Dominic Keller"

**Comment by serpams** [comment]
@pabloedu01 
![image](https://user-images.githubusercontent.com/25011754/185286669-8304e86f-7794-4a42-ab25-22bb3319fa4e.png)
Rota Check Token , não está sendo encontrada/ 
![image](https://user-images.githubusercontent.com/25011754/185287134-a3e255fe-c157-4c85-b7c6-4aa82d25b908.png)
Verificando no backend ela não retorna nada ainda
o ideal seria um retorno com O nome do Usuario , id , email e etc para persistir no frontend toda vez que validasse , pois no login pode ser que o token ainda esteja valido e o usuario não fez login naquele momento  e gera um undefined no nome do usuário
ou deseja Manter a persistencia de nome email apenas no login ?

**Comment by serpams** [comment]
[ead6c7b](https://github.com/TUNAP-Brasil/vehicle_control/commit/ead6c7b73876468d4c00723abf8309d39c414915)
Realizado no commit acima

**Comment by pabloedu01** [comment]
Tudo certo.
