### ISSUE TITLE
Alterar tipo de tabela

### ISSUE THREAD

**Issue by pabloedu01** [TUNAP-Brasil/vehicle_control#31]
![image](https://user-images.githubusercontent.com/1905753/183679082-80a6a60e-8a33-4cb2-ac54-869962d7fbc1.png)

Alterar tabela atual para o modelo a seguir:

https://hyper-ashen.vercel.app/ui/tables/advanced
MULTIPLE ROW SELECTION
![image](https://user-images.githubusercontent.com/1905753/183679904-f9751d16-2fab-493b-8555-49073afdaab7.png)

**Comment by serpams** [comment]
@ccccastanho001  - troca em todas as  telas que tiverem esta tabela  
@pabloedu01  -  o componente indicado não possui filtro nem exclusão , logo deverá ser criado funções para isso correto ?

**Comment by pabloedu01** [comment]
Exato, por enquanto não precisa adicionar o filtro, depois que for trocado a tabela eu vou entrar com outra issue para adição de campo de busca.

**Comment by pabloedu01** [comment]
Tudo correto
