### ISSUE TITLE
FIX - Consultor técnico

### ISSUE THREAD

**Issue by pabloedu01** [TUNAP-Brasil/vehicle_control#88]
![image](https://user-images.githubusercontent.com/1905753/218802050-08a46280-d5b6-45e1-be45-d98fe2bd1a9d.png)

Ao clicar em novo orçamento, deve-se legar também o consultor técnico que está no agendamento.

**Comment by kleberfreire** [comment]
![image](https://user-images.githubusercontent.com/32939737/219119995-b5ee5c27-9c80-420b-ac01-eea03820d0ed.png)

Já está sendo enviado.
