### ISSUE TITLE
FIX - Adicionar mode_id

### ISSUE THREAD

**Issue by pabloedu01** [TUNAP-Brasil/vehicle_control#90]
{{host}}/api/recommendation?company_id=2&model_id=1

adicionar model_id à consulta

**Comment by serpams** [comment]
feito no [0615c0f](https://github.com/TUNAP-Brasil/vehicle_control/commit/0615c0f7cc9b1b5fb13f2b1ffd2fbd0a44418bbc)

**Comment by pabloedu01** [comment]
![image](https://user-images.githubusercontent.com/1905753/219450288-d64d01b4-bf17-4090-aa4a-57b7936039fb.png)
Manter a opção de consultar apenas com o código da empresa.
